name: Automated Testing

on:
  push:
    branches:
      - main
      - roms-testing
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: dafyddstephenson/ucla-roms
        ref: roms-testing

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: ci/environment.yml

    - name: Create Conda Environment
      run: conda env create -f ci/environment.yml
      shell: bash

    - name: Initialize Conda
      run: conda init bash
      shell: bash

    - name: Activate Conda Environment
      run: |
        source $HOME/.bashrc
        conda activate roms-ci
        echo "The Conda prefix is ${CONDA_PREFIX}"
        conda info	

    - name: Set Environment Variables
      run: |
        source $HOME/.bashrc
        conda activate roms-ci      
        #source ci/set_environs.sh
        echo "The Conda prefix is ${CONDA_PREFIX}"
        conda info
        echo "export ROMS_ROOT=." >> $GITHUB_ENV
        echo "export MPIHOME=${CONDA_PREFIX}" >> $GITHUB_ENV
        echo "export NETCDFHOME=${CONDA_PREFIX}" >> $GITHUB_ENV
        echo "export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$NETCDFHOME/lib"" >> $GITHUB_ENV
        echo "export PATH="./:$PATH"" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ROMS_ROOT/Tools-Roms" >> $GITHUB_ENV
        echo "the github env variable is $GITHUB_ENV with contents"
        cat $GITHUB_ENV
      shell: bash
      
    - name: Compile Fortran Code
      run: |
        source $HOME/.bashrc
        conda activate roms-ci            	
        cd Work/
        echo "the github env variable is $GITHUB_ENV"
        make nhmg
      shell: bash

    - name: Run Tests
      run: bash Examples/code_check/do_test_all.sh
      shell: bash
